name: Default build-publish workflow

on: push

jobs:
  build-deploy:
    name: Build with CodeBuild and publish with CodeArtifact
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::660268862032:role/github-assume
          aws-region: us-east-1
