version: 0.2

phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - git config user.email "rustam21ashurmatov@gmail.com"
      - git config user.name "frixaco"
      - aws codeartifact login --tool npm --repository dev-api-client --domain frixaco --domain-owner 660268862032
  build:
    commands:
      - npm run build
      - npm version patch
      - npm publish --tag dev
artifacts:
  files:
    - "**/*"
  # name: api-client-live-$(date +%d%H%M)
  name: api-client-$(date +%d%H%M)
