name: Default build-publish workflow

on: push

jobs:
  build:
    name: Build with CodeBuild and publish with CodeArtifact
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-20.04
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::660268862032:role/github-assume
          aws-region: us-east-1
      - run: aws sts get-caller-identity